### ISSUE TITLE
Integrate Rubocop into the project

### ISSUE THREAD

**Issue by jcouball** [ruby-git/ruby-git#549]
### Integrate Rubocop into this project

I propose that we integrate Rubocop into this project in order to promote more consistent code style and to increase our CodeClimate maintainability score (which is currently a "C").

Many times when I make code changes, my editor removes spaces at the end of lines, spaces from otherwise blank lines or converts tabs to spaces which clutters the diff output. I think that integrating Rubocop will help with this problem.

I propose the following Rubocop configuration which mostly takes the Rubocop defaults:

```YAML
AllCops:
  # Output extra information for each offense to make it easier to diagnose:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  # RuboCop enforces rules depending on the oldest version of Ruby which
  # your project supports:
  TargetRubyVersion: 2.3

# The default max line length is 80 characters
Layout/LineLength:
  Max: 120

# The DSL for the gemspec file make it very hard to limit block length:
Metrics/BlockLength:
  Exclude:
    - "*.gemspec"

# When writing minitest tests, it is very hard to limit test class length:
Metrics/ClassLength:
  Exclude:
    - "test/**/*_test.rb"
```
